name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun i

      - name: Lint
        run: bun lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest is not supported yet
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun i

      - name: Build
        run: bun build:dev

      - name: Test
        run: bun test
